# Generated by Django 3.2.15 on 2023-06-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceAndConfirmedTop10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=32, unique=True)),
                ('confirmed', models.IntegerField()),
            ],
        ),
    ]
