# Generated by Django 3.2.15 on 2023-06-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_provinceandconfirmedtop10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceandconfirmedtop10',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
